/* THIS IS AUTO GENERATED CODE */

#ifndef __PIN_H__
#define __PIN_H__

#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>

/* port A definition */
#define PCB_VER0_PORT		GPIOA
#define PCB_VER0_PIN		GPIO0
#define PCB_VER0_EXTI		EXTI0
#define BOM_VER0_PORT		GPIOA
#define BOM_VER0_PIN		GPIO1
#define BOM_VER0_EXTI		EXTI1
#define MCU_UART1_TX_PORT		GPIOA
#define MCU_UART1_TX_PIN		GPIO2
#define MCU_UART1_TX_EXTI		EXTI2
#define MCU_UART1_RX_PORT		GPIOA
#define MCU_UART1_RX_PIN		GPIO3
#define MCU_UART1_RX_EXTI		EXTI3
#define CONN_PCIE_RST_N_RC_L_PORT		GPIOA
#define CONN_PCIE_RST_N_RC_L_PIN		GPIO4
#define CONN_PCIE_RST_N_RC_L_EXTI		EXTI4
#define PG_VDD_TPU_PORT		GPIOA
#define PG_VDD_TPU_PIN		GPIO5
#define PG_VDD_TPU_EXTI		EXTI5
#define PCIEE_RST_X_MCU_PORT		GPIOA
#define PCIEE_RST_X_MCU_PIN		GPIO6
#define PCIEE_RST_X_MCU_EXTI		EXTI6
#define I_3V3_PORT		GPIOA
#define I_3V3_PIN		GPIO7
#define I_3V3_EXTI		EXTI7
#define SYS_RST_X_PORT		GPIOA
#define SYS_RST_X_PIN		GPIO8
#define SYS_RST_X_EXTI		EXTI8
#define EN_VDDC_PORT		GPIOA
#define EN_VDDC_PIN		GPIO10
#define EN_VDDC_EXTI		EXTI10
#define EN_VDD_TPU_PORT		GPIOA
#define EN_VDD_TPU_PIN		GPIO11
#define EN_VDD_TPU_EXTI		EXTI11
#define SMB_CLK_PORT		GPIOA
#define SMB_CLK_PIN		GPIO12
#define SMB_CLK_EXTI		EXTI12
#define SWDIO_PORT		GPIOA
#define SWDIO_PIN		GPIO13
#define SWDIO_EXTI		EXTI13
#define SWCLK_PORT		GPIOA
#define SWCLK_PIN		GPIO14
#define SWCLK_EXTI		EXTI14
#define EN_VDDIO33_PORT		GPIOA
#define EN_VDDIO33_PIN		GPIO15
#define EN_VDDIO33_EXTI		EXTI15

/* port B definition */
#define GPIO1_PORT		GPIOB
#define GPIO1_PIN		GPIO0
#define GPIO1_EXTI		EXTI0
#define GPIO2_PORT		GPIOB
#define GPIO2_PIN		GPIO1
#define GPIO2_EXTI		EXTI1
#define GPIO3_PORT		GPIOB
#define GPIO3_PIN		GPIO2
#define GPIO3_EXTI		EXTI2
#define P08_PWR_GOOD_PORT		GPIOB
#define P08_PWR_GOOD_PIN		GPIO3
#define P08_PWR_GOOD_EXTI		EXTI3
#define DDR_PWR_GOOD_PORT		GPIOB
#define DDR_PWR_GOOD_PIN		GPIO4
#define DDR_PWR_GOOD_EXTI		EXTI4
#define PWM_VDDC_PORT		GPIOB
#define PWM_VDDC_PIN		GPIO5
#define PWM_VDDC_EXTI		EXTI5
#define I2C1_SCL_PORT		GPIOB
#define I2C1_SCL_PIN		GPIO6
#define I2C1_SCL_EXTI		EXTI6
#define I2C1_SDA_PORT		GPIOB
#define I2C1_SDA_PIN		GPIO7
#define I2C1_SDA_EXTI		EXTI7
#define STATUS_LED0_PORT		GPIOB
#define STATUS_LED0_PIN		GPIO8
#define STATUS_LED0_EXTI		EXTI8
#define MCU_I2C2_SCL_PORT		GPIOB
#define MCU_I2C2_SCL_PIN		GPIO10
#define MCU_I2C2_SCL_EXTI		EXTI10
#define MCU_I2C2_SDA_PORT		GPIOB
#define MCU_I2C2_SDA_PIN		GPIO11
#define MCU_I2C2_SDA_EXTI		EXTI11

/* port C definition */
#define PG_VDDC_PORT		GPIOC
#define PG_VDDC_PIN		GPIO14
#define PG_VDDC_EXTI		EXTI14
#define SMB_DATA_PORT		GPIOC
#define SMB_DATA_PIN		GPIO15
#define SMB_DATA_EXTI		EXTI15

void pin_init(void);

#endif
/* AUTO GENERATED CODE END */
