/* THIS IS AUTO GENERATED CODE */

#ifndef __PIN_H__
#define __PIN_H__

#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>

/* port A definition */
#define PCV_VER0_PORT		GPIOA
#define PCV_VER0_PIN		GPIO0
#define PCV_VER0_EXTI		EXTI0
#define BOM_VER0_PORT		GPIOA
#define BOM_VER0_PIN		GPIO1
#define BOM_VER0_EXTI		EXTI1
#define MCU_LED_PORT		GPIOA
#define MCU_LED_PIN		GPIO2
#define MCU_LED_EXTI		EXTI2
#define ASM3142_3P3V_EN_PORT		GPIOA
#define ASM3142_3P3V_EN_PIN		GPIO3
#define ASM3142_3P3V_EN_EXTI		EXTI3
#define I_12V_PORT		GPIOA
#define I_12V_PIN		GPIO4
#define I_12V_EXTI		EXTI4
#define PG_VDD_TPU_PORT		GPIOA
#define PG_VDD_TPU_PIN		GPIO5
#define PG_VDD_TPU_EXTI		EXTI5
#define PG_VDD_TPU_MEM_PORT		GPIOA
#define PG_VDD_TPU_MEM_PIN		GPIO6
#define PG_VDD_TPU_MEM_EXTI		EXTI6
#define NTC_MON_PORT		GPIOA
#define NTC_MON_PIN		GPIO7
#define NTC_MON_EXTI		EXTI7
#define VDD1P2V_EN_PORT		GPIOA
#define VDD1P2V_EN_PIN		GPIO8
#define VDD1P2V_EN_EXTI		EXTI8
#define EN_VQPS18_PORT		GPIOA
#define EN_VQPS18_PIN		GPIO9
#define EN_VQPS18_EXTI		EXTI9
#define P08_PG_PORT		GPIOA
#define P08_PG_PIN		GPIO10
#define P08_PG_EXTI		EXTI10
#define GPIO1_PORT		GPIOA
#define GPIO1_PIN		GPIO11
#define GPIO1_EXTI		EXTI11
#define SYS_RST_PORT		GPIOA
#define SYS_RST_PIN		GPIO12
#define SYS_RST_EXTI		EXTI12
#define SWDIO_PORT		GPIOA
#define SWDIO_PIN		GPIO13
#define SWDIO_EXTI		EXTI13
#define SWDCLK_PORT		GPIOA
#define SWDCLK_PIN		GPIO14
#define SWDCLK_EXTI		EXTI14
#define DDR_PG_PORT		GPIOA
#define DDR_PG_PIN		GPIO15
#define DDR_PG_EXTI		EXTI15

/* port B definition */
#define EN_VDDIO33_PORT		GPIOB
#define EN_VDDIO33_PIN		GPIO0
#define EN_VDDIO33_EXTI		EXTI0
#define EN_VDD_TPU_MEM_PORT		GPIOB
#define EN_VDD_TPU_MEM_PIN		GPIO1
#define EN_VDD_TPU_MEM_EXTI		EXTI1
#define GPIO2_PORT		GPIOB
#define GPIO2_PIN		GPIO2
#define GPIO2_EXTI		EXTI2
#define GPIO3_PORT		GPIOB
#define GPIO3_PIN		GPIO3
#define GPIO3_EXTI		EXTI3
#define EN_VDDIO18_PORT		GPIOB
#define EN_VDDIO18_PIN		GPIO4
#define EN_VDDIO18_EXTI		EXTI4
#define EN_VDD_TPU_PORT		GPIOB
#define EN_VDD_TPU_PIN		GPIO5
#define EN_VDD_TPU_EXTI		EXTI5
#define I2C1_SCL_MCU_PORT		GPIOB
#define I2C1_SCL_MCU_PIN		GPIO6
#define I2C1_SCL_MCU_EXTI		EXTI6
#define I2C1_SDA_MCU_PORT		GPIOB
#define I2C1_SDA_MCU_PIN		GPIO7
#define I2C1_SDA_MCU_EXTI		EXTI7
#define POWER_LED_PORT		GPIOB
#define POWER_LED_PIN		GPIO8
#define POWER_LED_EXTI		EXTI8
#define EN_VDDC_PORT		GPIOB
#define EN_VDDC_PIN		GPIO9
#define EN_VDDC_EXTI		EXTI9
#define PMIC_SCL_PORT		GPIOB
#define PMIC_SCL_PIN		GPIO10
#define PMIC_SCL_EXTI		EXTI10
#define PMIC_SDA_PORT		GPIOB
#define PMIC_SDA_PIN		GPIO11
#define PMIC_SDA_EXTI		EXTI11
#define RESET_KEY_PORT		GPIOB
#define RESET_KEY_PIN		GPIO12
#define RESET_KEY_EXTI		EXTI12
#define POWER_ON_PORT		GPIOB
#define POWER_ON_PIN		GPIO13
#define POWER_ON_EXTI		EXTI13
#define THERMAL_OFF_PORT		GPIOB
#define THERMAL_OFF_PIN		GPIO14
#define THERMAL_OFF_EXTI		EXTI14
#define PMEB_PORT		GPIOB
#define PMEB_PIN		GPIO15
#define PMEB_EXTI		EXTI15

/* port C definition */
#define HEALTHY_LED_PORT		GPIOC
#define HEALTHY_LED_PIN		GPIO13
#define HEALTHY_LED_EXTI		EXTI13
#define VDDC_SEL_PORT		GPIOC
#define VDDC_SEL_PIN		GPIO14
#define VDDC_SEL_EXTI		EXTI14
#define PG_VDDC_PORT		GPIOC
#define PG_VDDC_PIN		GPIO15
#define PG_VDDC_EXTI		EXTI15

/* port H definition */
#define USB_5V_EN_PORT		GPIOH
#define USB_5V_EN_PIN		GPIO0
#define USB_5V_EN_EXTI		EXTI0
#define DVDD_3P3V_EN_PORT		GPIOH
#define DVDD_3P3V_EN_PIN		GPIO1
#define DVDD_3P3V_EN_EXTI		EXTI1

void pin_init(void);

#endif
/* AUTO GENERATED CODE END */
