#ifndef __INFO_H__
#define __INFO_H__

#define DATA_EEPROM_BASE	(0x08080000)
#define DATA_EEPROM_BANK_SIZE	(3 * 1024)
#define DATA_EEPROM_BANK1	(DATA_EEPROM_BASE)
#define DATA_EEPROM_BANK2	(DATA_EEPROM_BANK1 + DATA_EEPROM_BANK_SIZE)

#define MCU_INFO_CELL_SIZE	(32)

#define MCU_INFO_BASE		((volatile unsigned char *)(DATA_EEPROM_BANK2))
#define MCU_INFO_MAC0		(MCU_INFO_BASE + MCU_INFO_CELL_SIZE * 0)
#define MCU_INFO_MAC1		(MCU_INFO_BASE + MCU_INFO_CELL_SIZE * 1)
#define MCU_INFO_SN		(MCU_INFO_BASE + MCU_INFO_CELL_SIZE * 2)
#define MCU_INFO_PROJ		(MCU_INFO_BASE + MCU_INFO_CELL_SIZE * 3)

extern int stage;

#endif
