/* THIS IS AUTO GENERATED CODE */

#ifndef __PIN_H__
#define __PIN_H__

#include <gd32e50x_gpio.h>

/* port A definition */
#define PCB_VER_PORT		GPIOA
#define PCB_VER_PIN		GPIO_PIN_0
#define PCB_VER_EXTI		EXTI_0
#define BOM_VER_PORT		GPIOA
#define BOM_VER_PIN		GPIO_PIN_1
#define BOM_VER_EXTI		EXTI_1
#define PG_VDD_PHY_PORT		GPIOA
#define PG_VDD_PHY_PIN		GPIO_PIN_2
#define PG_VDD_PHY_EXTI		EXTI_2
#define PG_VDDIO18_PORT		GPIOA
#define PG_VDDIO18_PIN		GPIO_PIN_3
#define PG_VDDIO18_EXTI		EXTI_3
#define ADC_V12_PORT		GPIOA
#define ADC_V12_PIN		GPIO_PIN_4
#define ADC_V12_EXTI		EXTI_4
#define LED_PORT		GPIOA
#define LED_PIN		GPIO_PIN_5
#define LED_EXTI		EXTI_5
#define ALERT_PORT		GPIOA
#define ALERT_PIN		GPIO_PIN_6
#define ALERT_EXTI		EXTI_6
#define GPIO1_PORT		GPIOA
#define GPIO1_PIN		GPIO_PIN_7
#define GPIO1_EXTI		EXTI_7
#define I2C2_SCL_PORT		GPIOA
#define I2C2_SCL_PIN		GPIO_PIN_8
#define I2C2_SCL_EXTI		EXTI_8
#define GPIO2_PORT		GPIOA
#define GPIO2_PIN		GPIO_PIN_9
#define GPIO2_EXTI		EXTI_9
#define GPIO3_PORT		GPIOA
#define GPIO3_PIN		GPIO_PIN_10
#define GPIO3_EXTI		EXTI_10
#define P08_PWR_GOOD_PORT		GPIOA
#define P08_PWR_GOOD_PIN		GPIO_PIN_11
#define P08_PWR_GOOD_EXTI		EXTI_11
#define DDR_PWR_GOOD_PORT		GPIOA
#define DDR_PWR_GOOD_PIN		GPIO_PIN_12
#define DDR_PWR_GOOD_EXTI		EXTI_12
#define PG_VDDIO33_PORT		GPIOA
#define PG_VDDIO33_PIN		GPIO_PIN_15
#define PG_VDDIO33_EXTI		EXTI_15

/* port B definition */
#define EN_VDD_TPU_PORT		GPIOB
#define EN_VDD_TPU_PIN		GPIO_PIN_0
#define EN_VDD_TPU_EXTI		EXTI_0
#define EN_VDDC_PORT		GPIOB
#define EN_VDDC_PIN		GPIO_PIN_1
#define EN_VDDC_EXTI		EXTI_1
#define PG_VDD_TPU_MEM_PORT		GPIOB
#define PG_VDD_TPU_MEM_PIN		GPIO_PIN_2
#define PG_VDD_TPU_MEM_EXTI		EXTI_2
#define EN_VQPS18_PORT		GPIOB
#define EN_VQPS18_PIN		GPIO_PIN_3
#define EN_VQPS18_EXTI		EXTI_3
#define I2C2_SDA_PORT		GPIOB
#define I2C2_SDA_PIN		GPIO_PIN_4
#define I2C2_SDA_EXTI		EXTI_4
#define TWARN_VDD_TPU_PORT		GPIOB
#define TWARN_VDD_TPU_PIN		GPIO_PIN_5
#define TWARN_VDD_TPU_EXTI		EXTI_5
#define EN_VDD_TPU_MEM_PORT		GPIOB
#define EN_VDD_TPU_MEM_PIN		GPIO_PIN_6
#define EN_VDD_TPU_MEM_EXTI		EXTI_6
#define PG_VDD_PCIE_PORT		GPIOB
#define PG_VDD_PCIE_PIN		GPIO_PIN_7
#define PG_VDD_PCIE_EXTI		EXTI_7
#define I2C0_SCL_PORT		GPIOB
#define I2C0_SCL_PIN		GPIO_PIN_8
#define I2C0_SCL_EXTI		EXTI_8
#define I2C0_SDA_PORT		GPIOB
#define I2C0_SDA_PIN		GPIO_PIN_9
#define I2C0_SDA_EXTI		EXTI_9
#define I2C1_SCL_PORT		GPIOB
#define I2C1_SCL_PIN		GPIO_PIN_10
#define I2C1_SCL_EXTI		EXTI_10
#define I2C1_SDA_PORT		GPIOB
#define I2C1_SDA_PIN		GPIO_PIN_11
#define I2C1_SDA_EXTI		EXTI_11
#define EN_VDDIO18_PORT		GPIOB
#define EN_VDDIO18_PIN		GPIO_PIN_12
#define EN_VDDIO18_EXTI		EXTI_12
#define EN_VDDIO33_PORT		GPIOB
#define EN_VDDIO33_PIN		GPIO_PIN_13
#define EN_VDDIO33_EXTI		EXTI_13
#define EN_VDD_PHY_PORT		GPIOB
#define EN_VDD_PHY_PIN		GPIO_PIN_14
#define EN_VDD_PHY_EXTI		EXTI_14
#define EN_VDD_PCIE_PORT		GPIOB
#define EN_VDD_PCIE_PIN		GPIO_PIN_15
#define EN_VDD_PCIE_EXTI		EXTI_15

/* port C definition */
#define SYS_RST_PORT		GPIOC
#define SYS_RST_PIN		GPIO_PIN_13
#define SYS_RST_EXTI		EXTI_13
#define PCIE_ERST_PORT		GPIOC
#define PCIE_ERST_PIN		GPIO_PIN_14
#define PCIE_ERST_EXTI		EXTI_14
#define PMIC_INT_PORT		GPIOC
#define PMIC_INT_PIN		GPIO_PIN_15
#define PMIC_INT_EXTI		EXTI_15

/* port D definition */
#define PG_VDDC_PORT		GPIOD
#define PG_VDDC_PIN		GPIO_PIN_0
#define PG_VDDC_EXTI		EXTI_0
#define PG_VDD_TPU_PORT		GPIOD
#define PG_VDD_TPU_PIN		GPIO_PIN_1
#define PG_VDD_TPU_EXTI		EXTI_1

#endif
/* AUTO GENERATED CODE END */
