/* THIS IS AUTO GENERATED CODE */

#ifndef __PIN_H__
#define __PIN_H__

#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>

/* port A definition */
#define BOM_VER_PORT		GPIOA
#define BOM_VER_PIN		GPIO0
#define BOM_VER_EXTI		EXTI0
#define CURRENT_SYS_12V_PORT		GPIOA
#define CURRENT_SYS_12V_PIN		GPIO1
#define CURRENT_SYS_12V_EXTI		EXTI1
#define MCU_UART2_TX_PORT		GPIOA
#define MCU_UART2_TX_PIN		GPIO2
#define MCU_UART2_TX_EXTI		EXTI2
#define MCU_UART2_RX_PORT		GPIOA
#define MCU_UART2_RX_PIN		GPIO3
#define MCU_UART2_RX_EXTI		EXTI3
#define TPU_PG_2_PORT		GPIOA
#define TPU_PG_2_PIN		GPIO4
#define TPU_PG_2_EXTI		EXTI4
#define TPUMEM_PG_2_PORT		GPIOA
#define TPUMEM_PG_2_PIN		GPIO5
#define TPUMEM_PG_2_EXTI		EXTI5
#define DDR_PG_2_PORT		GPIOA
#define DDR_PG_2_PIN		GPIO6
#define DDR_PG_2_EXTI		EXTI6
#define BOOT_RECOVERYB0_PORT		GPIOA
#define BOOT_RECOVERYB0_PIN		GPIO8
#define BOOT_RECOVERYB0_EXTI		EXTI8
#define MCU_UART1_TX_PORT		GPIOA
#define MCU_UART1_TX_PIN		GPIO9
#define MCU_UART1_TX_EXTI		EXTI9
#define MCU_UART1_RX_PORT		GPIOA
#define MCU_UART1_RX_PIN		GPIO10
#define MCU_UART1_RX_EXTI		EXTI10
#define I2C_A0_PORT		GPIOA
#define I2C_A0_PIN		GPIO11
#define I2C_A0_EXTI		EXTI11
#define I2C_A1_PORT		GPIOA
#define I2C_A1_PIN		GPIO12
#define I2C_A1_EXTI		EXTI12
#define B2_SYS_RST_N_PORT		GPIOA
#define B2_SYS_RST_N_PIN		GPIO15
#define B2_SYS_RST_N_EXTI		EXTI15

/* port B definition */
#define B6_SYS_RST_N_PORT		GPIOB
#define B6_SYS_RST_N_PIN		GPIO0
#define B6_SYS_RST_N_EXTI		EXTI0
#define B7_SYS_RST_N_PORT		GPIOB
#define B7_SYS_RST_N_PIN		GPIO1
#define B7_SYS_RST_N_EXTI		EXTI1
#define EN_VDD_PHY_PORT		GPIOB
#define EN_VDD_PHY_PIN		GPIO2
#define EN_VDD_PHY_EXTI		EXTI2
#define B7_MCU_ALERT_PORT		GPIOB
#define B7_MCU_ALERT_PIN		GPIO3
#define B7_MCU_ALERT_EXTI		EXTI3
#define B6_MCU_ALERT_PORT		GPIOB
#define B6_MCU_ALERT_PIN		GPIO4
#define B6_MCU_ALERT_EXTI		EXTI4
#define B5_MCU_ALERT_PORT		GPIOB
#define B5_MCU_ALERT_PIN		GPIO5
#define B5_MCU_ALERT_EXTI		EXTI5
#define B4_MCU_ALERT_PORT		GPIOB
#define B4_MCU_ALERT_PIN		GPIO6
#define B4_MCU_ALERT_EXTI		EXTI6
#define B3_MCU_ALERT_PORT		GPIOB
#define B3_MCU_ALERT_PIN		GPIO7
#define B3_MCU_ALERT_EXTI		EXTI7
#define MCU_IIC1_SCL_PORT		GPIOB
#define MCU_IIC1_SCL_PIN		GPIO8
#define MCU_IIC1_SCL_EXTI		EXTI8
#define MCU_IIC1_SDA_PORT		GPIOB
#define MCU_IIC1_SDA_PIN		GPIO9
#define MCU_IIC1_SDA_EXTI		EXTI9
#define MCU_IIC2_SCL_PORT		GPIOB
#define MCU_IIC2_SCL_PIN		GPIO10
#define MCU_IIC2_SCL_EXTI		EXTI10
#define MCU_IIC2_SDA_PORT		GPIOB
#define MCU_IIC2_SDA_PIN		GPIO11
#define MCU_IIC2_SDA_EXTI		EXTI11
#define DDR_PG_1_PORT		GPIOB
#define DDR_PG_1_PIN		GPIO12
#define DDR_PG_1_EXTI		EXTI12
#define INT_PMIC_B5678_PORT		GPIOB
#define INT_PMIC_B5678_PIN		GPIO13
#define INT_PMIC_B5678_EXTI		EXTI13
#define EN_VDDC_PORT		GPIOB
#define EN_VDDC_PIN		GPIO14
#define EN_VDDC_EXTI		EXTI14
#define EN_VDD_TPU_PORT		GPIOB
#define EN_VDD_TPU_PIN		GPIO15
#define EN_VDD_TPU_EXTI		EXTI15

/* port C definition */
#define MCU_IIC3_SCL_PORT		GPIOC
#define MCU_IIC3_SCL_PIN		GPIO0
#define MCU_IIC3_SCL_EXTI		EXTI0
#define MCU_IIC3_SDA_PORT		GPIOC
#define MCU_IIC3_SDA_PIN		GPIO1
#define MCU_IIC3_SDA_EXTI		EXTI1
#define CURRENT_PCIE_12V_PORT		GPIOC
#define CURRENT_PCIE_12V_PIN		GPIO2
#define CURRENT_PCIE_12V_EXTI		EXTI2
#define CURRENT_PCIE_3V3_PORT		GPIOC
#define CURRENT_PCIE_3V3_PIN		GPIO3
#define CURRENT_PCIE_3V3_EXTI		EXTI3
#define B5_SYS_RST_N_PORT		GPIOC
#define B5_SYS_RST_N_PIN		GPIO4
#define B5_SYS_RST_N_EXTI		EXTI4
#define HW_VER_PORT		GPIOC
#define HW_VER_PIN		GPIO5
#define HW_VER_EXTI		EXTI5
#define B3_SYS_RST_N_PORT		GPIOC
#define B3_SYS_RST_N_PIN		GPIO7
#define B3_SYS_RST_N_EXTI		EXTI7
#define PG_VDDC_B5678_PORT		GPIOC
#define PG_VDDC_B5678_PIN		GPIO8
#define PG_VDDC_B5678_EXTI		EXTI8
#define BOOT_RECOVERYB1_PORT		GPIOC
#define BOOT_RECOVERYB1_PIN		GPIO9
#define BOOT_RECOVERYB1_EXTI		EXTI9
#define PCIE_SYS_RST_N_PORT		GPIOC
#define PCIE_SYS_RST_N_PIN		GPIO13
#define PCIE_SYS_RST_N_EXTI		EXTI13
#define PCIE_PG_1_PORT		GPIOC
#define PCIE_PG_1_PIN		GPIO14
#define PCIE_PG_1_EXTI		EXTI14
#define TPU_PG_1_PORT		GPIOC
#define TPU_PG_1_PIN		GPIO15
#define TPU_PG_1_EXTI		EXTI15

/* port D definition */
#define B1_SYS_RST_N_PORT		GPIOD
#define B1_SYS_RST_N_PIN		GPIO0
#define B1_SYS_RST_N_EXTI		EXTI0
#define PG_VDD_PHY_B5678_PORT		GPIOD
#define PG_VDD_PHY_B5678_PIN		GPIO3
#define PG_VDD_PHY_B5678_EXTI		EXTI3
#define PG_VDD_PHY_B1234_PORT		GPIOD
#define PG_VDD_PHY_B1234_PIN		GPIO4
#define PG_VDD_PHY_B1234_EXTI		EXTI4
#define B4_SYS_RST_N_PORT		GPIOD
#define B4_SYS_RST_N_PIN		GPIO5
#define B4_SYS_RST_N_EXTI		EXTI5
#define PG_PCIE_0V84_PORT		GPIOD
#define PG_PCIE_0V84_PIN		GPIO6
#define PG_PCIE_0V84_EXTI		EXTI6
#define B8_MCU_ALERT_PORT		GPIOD
#define B8_MCU_ALERT_PIN		GPIO7
#define B8_MCU_ALERT_EXTI		EXTI7
#define INT_PMIC_B1234_PORT		GPIOD
#define INT_PMIC_B1234_PIN		GPIO8
#define INT_PMIC_B1234_EXTI		EXTI8
#define PG_PMIC_B1234_PORT		GPIOD
#define PG_PMIC_B1234_PIN		GPIO11
#define PG_PMIC_B1234_EXTI		EXTI11
#define PG_VDD_TPU_B5678_PORT		GPIOD
#define PG_VDD_TPU_B5678_PIN		GPIO12
#define PG_VDD_TPU_B5678_EXTI		EXTI12
#define PG_VDD_TPU_B1234_PORT		GPIOD
#define PG_VDD_TPU_B1234_PIN		GPIO13
#define PG_VDD_TPU_B1234_EXTI		EXTI13
#define PG_PMIC_B5678_PORT		GPIOD
#define PG_PMIC_B5678_PIN		GPIO14
#define PG_PMIC_B5678_EXTI		EXTI14

/* port E definition */
#define B2_MCU_ALERT_PORT		GPIOE
#define B2_MCU_ALERT_PIN		GPIO0
#define B2_MCU_ALERT_EXTI		EXTI0
#define B1_MCU_ALERT_PORT		GPIOE
#define B1_MCU_ALERT_PIN		GPIO1
#define B1_MCU_ALERT_EXTI		EXTI1
#define P08_PG_1_PORT		GPIOE
#define P08_PG_1_PIN		GPIO3
#define P08_PG_1_EXTI		EXTI3
#define P08_PG_2_PORT		GPIOE
#define P08_PG_2_PIN		GPIO5
#define P08_PG_2_EXTI		EXTI5
#define PCIE_PG_2_PORT		GPIOE
#define PCIE_PG_2_PIN		GPIO6
#define PCIE_PG_2_EXTI		EXTI6
#define MCU_UART4_TX_PORT		GPIOE
#define MCU_UART4_TX_PIN		GPIO8
#define MCU_UART4_TX_EXTI		EXTI8
#define MCU_UART4_RX_PORT		GPIOE
#define MCU_UART4_RX_PIN		GPIO9
#define MCU_UART4_RX_EXTI		EXTI9
#define PWR_DET0_PORT		GPIOE
#define PWR_DET0_PIN		GPIO11
#define PWR_DET0_EXTI		EXTI11
#define PWR_DET1_PORT		GPIOE
#define PWR_DET1_PIN		GPIO12
#define PWR_DET1_EXTI		EXTI12
#define B8_SYS_RST_N_PORT		GPIOE
#define B8_SYS_RST_N_PIN		GPIO13
#define B8_SYS_RST_N_EXTI		EXTI13
#define EN_VDDIO33_PORT		GPIOE
#define EN_VDDIO33_PIN		GPIO14
#define EN_VDDIO33_EXTI		EXTI14
#define PG_VDDC_B1234_PORT		GPIOE
#define PG_VDDC_B1234_PIN		GPIO15
#define PG_VDDC_B1234_EXTI		EXTI15

/* port H definition */
#define PCIE_MCU_RST_X_PORT		GPIOE
#define PCIE_MCU_RST_X_PIN		GPIO0
#define PCIE_MCU_RST_X_EXTI		EXTI0
#define TPUMEM_PG_1_PORT		GPIOE
#define TPUMEM_PG_1_PIN		GPIO1
#define TPUMEM_PG_1_EXTI		EXTI1

void pin_init(void);

#endif
/* AUTO GENERATED CODE END */
