#include "gd32f4xx.h"
#include "sc11e_en.h"
#include "systick.h"

static void sc11e_en_gpio_clock(void);
static void sc11e_config_gpio_pin(void);
static void sc11e_power_on(void);

void sc11e_en_start(void)
{
	systick_config();
	sc11e_en_gpio_clock();
	sc11e_config_gpio_pin();
	sc11e_power_on();
}


static void sc11e_en_gpio_clock(void)
{
	RCU_AHB1EN |= RCU_GPIOA_CLOCK_BIT | RCU_GPIOB_CLOCK_BIT | RCU_GPIOC_CLOCK_BIT | RCU_GPIOC_CLOCK_BIT
		| RCU_GPIOD_CLOCK_BIT | RCU_GPIOE_CLOCK_BIT | RCU_GPIOF_CLOCK_BIT | RCU_GPIOG_CLOCK_BIT;
	(void)RCU_AHB1EN;
}


static void sc11e_config_gpio_pin(void)
{
	/*设置PA11,12,15期望电平*/
	GPIO_BOP(GPIOA) = GPIO_BOP_CR11 | GPIO_BOP_CR12 | GPIO_BOP_CR15;

	/*设置PB3,4,5,8,9,12,13,14,15期望电平*/
	GPIO_BOP(GPIOB) = GPIO_BOP_CR3 | GPIO_BOP_CR4 | GPIO_BOP_CR5 | GPIO_BOP_CR8 | GPIO_BOP_CR9 |
		GPIO_BOP_CR12 | GPIO_BOP_CR13 | GPIO_BOP_CR14 |GPIO_BOP_CR15;

	/*设置PC6,7,8,12,13,14,15期望电平*/
	GPIO_BOP(GPIOC) = GPIO_BOP_CR6 | GPIO_BOP_CR7 | GPIO_BOP_CR8 |
		GPIO_BOP_CR12 | GPIO_BOP_CR13 | GPIO_BOP_CR14 |GPIO_BOP_CR15;

	/*设置PD0,1,2,3,4,7,9,10,14期望电平*/
	GPIO_BOP(GPIOD) = GPIO_BOP_CR0 | GPIO_BOP_CR1 | GPIO_BOP_CR2 | GPIO_BOP_CR3 | GPIO_BOP_CR4 |
		GPIO_BOP_CR7 | GPIO_BOP_CR9 | GPIO_BOP_CR10 | GPIO_BOP_CR14;

	/*设置PA11,12,15推挽模式*/
	GPIO_OMODE(GPIOA) &= ~(GPIO_OMODE_OM11 | GPIO_OMODE_OM12 | GPIO_OMODE_OM15);

	/*设置PB3,4,5,8,9,12,13,14,15推挽模式*/
	GPIO_OMODE(GPIOB) &= ~(GPIO_OMODE_OM3 | GPIO_OMODE_OM4 | GPIO_OMODE_OM5 |GPIO_OMODE_OM8 |
			       GPIO_OMODE_OM9 | GPIO_OMODE_OM12| GPIO_OMODE_OM13 | GPIO_OMODE_OM14 | GPIO_OMODE_OM15);

	/*设置PC6,7,8,12,13,14,15推挽模式*/
	GPIO_OMODE(GPIOC) &= ~(GPIO_OMODE_OM6 | GPIO_OMODE_OM7 |GPIO_OMODE_OM8 |
			       GPIO_OMODE_OM12| GPIO_OMODE_OM13 | GPIO_OMODE_OM14 | GPIO_OMODE_OM15);

	/*设置PD0,1,2,3,4,7,9,10,14推挽模式*/
	GPIO_OMODE(GPIOD) &= ~(GPIO_OMODE_OM0 | GPIO_OMODE_OM1 | GPIO_OMODE_OM2 |GPIO_OMODE_OM3 |
			       GPIO_OMODE_OM4 | GPIO_OMODE_OM7| GPIO_OMODE_OM9 | GPIO_OMODE_OM10 | GPIO_OMODE_OM14);

	/*设置PA11,12,15 频率*/
	GPIO_OSPD(GPIOA) &= ~(GPIO_OSPD_MIN(22,23) | GPIO_OSPD_MIN(24,25) | GPIO_OSPD_MIN(30,31));
	GPIO_OSPD(GPIOA) |= GPIO_OSPD_MIN(22,23) | GPIO_OSPD_MIN(24,25) | GPIO_OSPD_MIN(30,31);

	/*设置PB3,4,5,8,9,12,13,14,15 频率*/
	GPIO_OSPD(GPIOB) &= ~(GPIO_OSPD_MIN(6,7) | GPIO_OSPD_MIN(8,9) | GPIO_OSPD_MIN(10,11) | GPIO_OSPD_MIN(16,17) |
		GPIO_OSPD_MIN(18,19) | GPIO_OSPD_MIN(24,25) | GPIO_OSPD_MIN(26,27) | GPIO_OSPD_MIN(28,29) |
		GPIO_OSPD_MIN(30,31));
	GPIO_OSPD(GPIOB) |= GPIO_OSPD_MIN(6,7) | GPIO_OSPD_MIN(8,9) | GPIO_OSPD_MIN(10,11) | GPIO_OSPD_MIN(16,17) |
		GPIO_OSPD_MIN(18,19) | GPIO_OSPD_MIN(24,25) | GPIO_OSPD_MIN(26,27) | GPIO_OSPD_MIN(28,29) |
		GPIO_OSPD_MIN(30,31);

	/*设置PC6,7,8,12,13,14,15 频率*/
	GPIO_OSPD(GPIOC) &= ~(GPIO_OSPD_MIN(12,13) | GPIO_OSPD_MIN(14,15) | GPIO_OSPD_MIN(16,17) |
		GPIO_OSPD_MIN(24,25) | GPIO_OSPD_MIN(26,27) | GPIO_OSPD_MIN(28,29) | GPIO_OSPD_MIN(30,31));
	GPIO_OSPD(GPIOC) |= GPIO_OSPD_MIN(12,13) | GPIO_OSPD_MIN(14,15) | GPIO_OSPD_MIN(16,17) |
		GPIO_OSPD_MIN(24,25) | GPIO_OSPD_MIN(26,27) | GPIO_OSPD_MIN(28,29) | GPIO_OSPD_MIN(30,31);

	/*设置PD0,1,2,3,4,7,9,10,14 频率*/
	GPIO_OSPD(GPIOD) &= ~(GPIO_OSPD_MIN(0,1) | GPIO_OSPD_MIN(2,3) | GPIO_OSPD_MIN(4,5) | GPIO_OSPD_MIN(6,7) |
		GPIO_OSPD_MIN(8,9) | GPIO_OSPD_MIN(14,15) | GPIO_OSPD_MIN(18,19) | GPIO_OSPD_MIN(20,21) |
		GPIO_OSPD_MIN(28,29));
	GPIO_OSPD(GPIOD) |= GPIO_OSPD_MIN(0,1) | GPIO_OSPD_MIN(2,3) | GPIO_OSPD_MIN(4,5) | GPIO_OSPD_MIN(6,7) |
		GPIO_OSPD_MIN(8,9) | GPIO_OSPD_MIN(14,15) | GPIO_OSPD_MIN(18,19) | GPIO_OSPD_MIN(20,21) |
		GPIO_OSPD_MIN(28,29);

	/*设置PA11,12,15 PULLDOWN*/
	GPIO_PUD(GPIOA) &= ~(GPIO_PUPD_PULLDOWN_PIN11 | GPIO_PUPD_PULLDOWN_PIN12 | GPIO_PUPD_PULLDOWN_PIN15);
	GPIO_PUD(GPIOA) |= GPIO_PUPD_PULLDOWN_PIN11 | GPIO_PUPD_PULLDOWN_PIN12 | GPIO_PUPD_PULLDOWN_PIN15;

	/*设置PB3,4,5,8,9,12,13,14,15 PULLDOWN*/
	GPIO_PUD(GPIOB) &= ~(GPIO_PUPD_PULLDOWN_PIN3 | GPIO_PUPD_PULLDOWN_PIN4 | GPIO_PUPD_PULLDOWN_PIN5 |
		GPIO_PUPD_PULLDOWN_PIN8 | GPIO_PUPD_PULLDOWN_PIN9 | GPIO_PUPD_PULLDOWN_PIN12 |
		GPIO_PUPD_PULLDOWN_PIN13 | GPIO_PUPD_PULLDOWN_PIN14 | GPIO_PUPD_PULLDOWN_PIN15);
	GPIO_PUD(GPIOB) |= GPIO_PUPD_PULLDOWN_PIN3 | GPIO_PUPD_PULLDOWN_PIN4 | GPIO_PUPD_PULLDOWN_PIN5 |
		GPIO_PUPD_PULLDOWN_PIN8 | GPIO_PUPD_PULLDOWN_PIN9 | GPIO_PUPD_PULLDOWN_PIN12 |
		GPIO_PUPD_PULLDOWN_PIN13 | GPIO_PUPD_PULLDOWN_PIN14 | GPIO_PUPD_PULLDOWN_PIN15;

	/*设置PC6,7,8,12,13,14,15 PULLDOWN*/
	GPIO_PUD(GPIOC) &= ~(GPIO_PUPD_PULLDOWN_PIN6 | GPIO_PUPD_PULLDOWN_PIN7 | GPIO_PUPD_PULLDOWN_PIN8 |
		GPIO_PUPD_PULLDOWN_PIN12 | GPIO_PUPD_PULLDOWN_PIN13 | GPIO_PUPD_PULLDOWN_PIN14 |
		GPIO_PUPD_PULLDOWN_PIN15);
	GPIO_PUD(GPIOC) |= GPIO_PUPD_PULLDOWN_PIN6 | GPIO_PUPD_PULLDOWN_PIN7 | GPIO_PUPD_PULLDOWN_PIN8 |
		GPIO_PUPD_PULLDOWN_PIN12 | GPIO_PUPD_PULLDOWN_PIN13 | GPIO_PUPD_PULLDOWN_PIN14 |
		GPIO_PUPD_PULLDOWN_PIN15;

	/*设置PD0,1,2,3,4,7,9,10,14 PULLDOWN*/
	GPIO_PUD(GPIOD) &= ~(GPIO_PUPD_PULLDOWN_PIN0 | GPIO_PUPD_PULLDOWN_PIN1 | GPIO_PUPD_PULLDOWN_PIN2 |
		GPIO_PUPD_PULLDOWN_PIN3 | GPIO_PUPD_PULLDOWN_PIN4 | GPIO_PUPD_PULLDOWN_PIN7 |
		GPIO_PUPD_PULLDOWN_PIN9 | GPIO_PUPD_PULLDOWN_PIN10 | GPIO_PUPD_PULLDOWN_PIN14);
	GPIO_PUD(GPIOD) |= GPIO_PUPD_PULLDOWN_PIN0 | GPIO_PUPD_PULLDOWN_PIN1 | GPIO_PUPD_PULLDOWN_PIN2 |
		GPIO_PUPD_PULLDOWN_PIN3 | GPIO_PUPD_PULLDOWN_PIN4 | GPIO_PUPD_PULLDOWN_PIN7 |
		GPIO_PUPD_PULLDOWN_PIN9 | GPIO_PUPD_PULLDOWN_PIN10 | GPIO_PUPD_PULLDOWN_PIN14;

	/*设置PA11,12,15 为输出模式*/
	GPIO_CTL(GPIOA) &= ~(GPIO_OUTPUT_PIN11 | GPIO_OUTPUT_PIN12 | GPIO_OUTPUT_PIN15);
	GPIO_CTL(GPIOA) |= (GPIO_OUTPUT_PIN11 | GPIO_OUTPUT_PIN12 | GPIO_OUTPUT_PIN15);

	/*设置PB3,4,5,8,9,12,13,14,15 为输出模式*/
	GPIO_CTL(GPIOB) &= ~(GPIO_OUTPUT_PIN3 | GPIO_OUTPUT_PIN4 | GPIO_OUTPUT_PIN5 | GPIO_OUTPUT_PIN8 | GPIO_OUTPUT_PIN9 |
			     GPIO_OUTPUT_PIN12 | GPIO_OUTPUT_PIN13 | GPIO_OUTPUT_PIN14 | GPIO_OUTPUT_PIN15);
	GPIO_CTL(GPIOB) |= (GPIO_OUTPUT_PIN3 | GPIO_OUTPUT_PIN4 | GPIO_OUTPUT_PIN5 | GPIO_OUTPUT_PIN8 | GPIO_OUTPUT_PIN9 |
			     GPIO_OUTPUT_PIN12 | GPIO_OUTPUT_PIN13 | GPIO_OUTPUT_PIN14 | GPIO_OUTPUT_PIN15);

	/*设置PC6,7,8,12,13,14,15 为输出模式*/
	GPIO_CTL(GPIOC) &= ~(GPIO_OUTPUT_PIN6 | GPIO_OUTPUT_PIN7 | GPIO_OUTPUT_PIN8 | GPIO_OUTPUT_PIN12 |
			     GPIO_OUTPUT_PIN13 | GPIO_OUTPUT_PIN14 | GPIO_OUTPUT_PIN15);
	GPIO_CTL(GPIOC) |= (GPIO_OUTPUT_PIN6 | GPIO_OUTPUT_PIN7 | GPIO_OUTPUT_PIN8 | GPIO_OUTPUT_PIN12 |
			     GPIO_OUTPUT_PIN13 | GPIO_OUTPUT_PIN14 | GPIO_OUTPUT_PIN15);

	/*设置PD0,1,2,3,4,7,9,10,14 为输出模式*/
	GPIO_CTL(GPIOD) &= ~(GPIO_OUTPUT_PIN0 | GPIO_OUTPUT_PIN1 | GPIO_OUTPUT_PIN2 | GPIO_OUTPUT_PIN3 | GPIO_OUTPUT_PIN4 |
			     GPIO_OUTPUT_PIN7 | GPIO_OUTPUT_PIN9 | GPIO_OUTPUT_PIN10 | GPIO_OUTPUT_PIN14);
	GPIO_CTL(GPIOD) |= (GPIO_OUTPUT_PIN0 | GPIO_OUTPUT_PIN1 | GPIO_OUTPUT_PIN2 | GPIO_OUTPUT_PIN3 | GPIO_OUTPUT_PIN4 |
			     GPIO_OUTPUT_PIN7 | GPIO_OUTPUT_PIN9 | GPIO_OUTPUT_PIN10 | GPIO_OUTPUT_PIN14);
}

static void sc11e_node_on(uint32_t port, uint32_t pin)
{
	GPIO_BOP(port) = pin;
}

static void sc11e_power_on(void)
{
	/* 使能 5V & 3V3 & PLL*/
	sc11e_node_on(GPIOA, GPIO_BOP_BOP12);
	sc11e_node_on(GPIOB, GPIO_BOP_BOP3);
	sc11e_node_on(GPIOC, GPIO_BOP_BOP6);
	sc11e_node_on(GPIOC, GPIO_BOP_BOP6);
	sc11e_node_on(GPIOD, GPIO_BOP_BOP9);
	delay_1ms(5);

	/* 使能 VDDC & VDDR & DDR_VDD*/
	sc11e_node_on(GPIOB, GPIO_BOP_BOP15);	// vddc bm0
	sc11e_node_on(GPIOD, GPIO_BOP_BOP7);	// vddc bm1
	sc11e_node_on(GPIOD, GPIO_BOP_BOP10);	// vddc bm2
	sc11e_node_on(GPIOD, GPIO_BOP_BOP14);	// vddc bm3
	sc11e_node_on(GPIOC, GPIO_BOP_BOP12);	// vddr bm0
	sc11e_node_on(GPIOC, GPIO_BOP_BOP13);	// vddr bm1
	sc11e_node_on(GPIOC, GPIO_BOP_BOP14);	// vddr bm2
	sc11e_node_on(GPIOC, GPIO_BOP_BOP15);	// vddr bm3
	sc11e_node_on(GPIOB, GPIO_BOP_BOP9);	// ddr_vdd bm01
	sc11e_node_on(GPIOD, GPIO_BOP_BOP1);	// ddr_vdd bm23
	delay_1ms(5);

	/* 使能 1V2 & 1V8*/
	sc11e_node_on(GPIOA, GPIO_BOP_BOP11);	// vdd 1V2
	sc11e_node_on(GPIOA, GPIO_BOP_BOP15);	// vdd 1V8
	delay_1ms(5);

	/* 使能 VPH PCIE & VP PCIE*/
	sc11e_node_on(GPIOA, GPIO_BOP_BOP15);	// VPH PCIE BM01
	sc11e_node_on(GPIOD, GPIO_BOP_BOP3);	// VPH PCIE BM23
	sc11e_node_on(GPIOB, GPIO_BOP_BOP14);	// VP PCIE BM01
	sc11e_node_on(GPIOD, GPIO_BOP_BOP4);	// VP PCIE BM23
	delay_1ms(5);

	/* 使能 DDR VAA*/
	sc11e_node_on(GPIOB, GPIO_BOP_BOP12);	// DDR VAA BM01
	sc11e_node_on(GPIOD, GPIO_BOP_BOP2);	// DDR VAA BM23
	delay_1ms(5);

	/* 使能 DDR VDD1*/
	sc11e_node_on(GPIOB, GPIO_BOP_BOP8);	// DDR VAA BM01
	sc11e_node_on(GPIOD, GPIO_BOP_BOP0);	// DDR VAA BM23
	delay_1ms(5);

	/* 使能 DDR_VDD2H*/
	sc11e_node_on(GPIOB, GPIO_BOP_BOP5);	// DDR VDD2H BM01
	sc11e_node_on(GPIOC, GPIO_BOP_BOP8);	// DDR VDD2H BM23
	delay_1ms(5);

	/* 使能 DDR_VDDQ*/
	sc11e_node_on(GPIOB, GPIO_BOP_BOP4);	// DDR VDDQ BM01
	sc11e_node_on(GPIOC, GPIO_BOP_BOP7);	// DDR VDDQ BM23
	delay_1ms(10);

	/* 使能 SYSRST*/
	sc11e_node_on(GPIOB, GPIO_BOP_BOP1);	// SYSRST BM0
	sc11e_node_on(GPIOB, GPIO_BOP_BOP0);	// SYSRST BM1
	sc11e_node_on(GPIOE, GPIO_BOP_BOP13);	// SYSRST BM1
	sc11e_node_on(GPIOE, GPIO_BOP_BOP12);	// SYSRST BM1
}
