#if 0
#define AHB1_BUS_BASE   ((uint32_t)0x40020000U)        /*!< ahb1 base address */
#define RCU_BASE        (AHB1_BUS_BASE + 0x00003800U)  /*!< RCU base address */
#define RCU		RCU_BASE
#define RCU_AHB1EN      REG32(RCU + 0x30U)        /*!< AHB1 enable register */

#define GPIO_BASE       (AHB1_BUS_BASE + 0x00000000U)  /*!< GPIO base address */
#define GPIOA		(GPIO_BASE + 0x00000000U)
#define GPIOB		(GPIO_BASE + 0x00000400U)
#define GPIOC		(GPIO_BASE + 0x00000800U)
#define GPIOD		(GPIO_BASE + 0x00000c00U)
#define GPIOE		(GPIO_BASE + 0x00001000U)
#define GPIOF		(GPIO_BASE + 0x00001400U)
#define GPIOG		(GPIO_BASE + 0x00001800U)
#define GPIOH		(GPIO_BASE + 0x00001c00U)
#define GPIOI		(GPIO_BASE + 0x00002000U)
#endif


#define RCU_GPIOA_CLOCK_BIT  (1U << 0)
#define RCU_GPIOB_CLOCK_BIT  (1U << 1)
#define RCU_GPIOC_CLOCK_BIT  (1U << 2)
#define RCU_GPIOD_CLOCK_BIT  (1U << 3)
#define RCU_GPIOE_CLOCK_BIT  (1U << 4)
#define RCU_GPIOF_CLOCK_BIT  (1U << 5)
#define RCU_GPIOG_CLOCK_BIT  (1U << 6)
#define RCU_GPIOH_CLOCK_BIT  (1U << 7)
#define RCU_GPIOI_CLOCK_BIT  (1U << 8)

#define GPIO_OSPD_MIN(start,end)	((0xFFFFFFFFUL << (start)) & (0xFFFFFFFFUL >> (31U - (uint32_t)(end-1))))


#define GPIO_PIN_PULLDOWN(start,end)	((0xFFFFFFFFUL << (start+1)) & (0xFFFFFFFFUL >> (31U - (uint32_t)(end))))
#define GPIO_PUPD_PULLDOWN_PIN0		GPIO_PIN_PULLDOWN(0,1)
#define GPIO_PUPD_PULLDOWN_PIN1		GPIO_PIN_PULLDOWN(2,3)
#define GPIO_PUPD_PULLDOWN_PIN2		GPIO_PIN_PULLDOWN(4,5)
#define GPIO_PUPD_PULLDOWN_PIN3		GPIO_PIN_PULLDOWN(6,7)
#define GPIO_PUPD_PULLDOWN_PIN4		GPIO_PIN_PULLDOWN(8,9)
#define GPIO_PUPD_PULLDOWN_PIN5		GPIO_PIN_PULLDOWN(10,11)
#define GPIO_PUPD_PULLDOWN_PIN6		GPIO_PIN_PULLDOWN(12,13)
#define GPIO_PUPD_PULLDOWN_PIN7		GPIO_PIN_PULLDOWN(14,15)
#define GPIO_PUPD_PULLDOWN_PIN8		GPIO_PIN_PULLDOWN(16,17)
#define GPIO_PUPD_PULLDOWN_PIN9		GPIO_PIN_PULLDOWN(18,19)
#define GPIO_PUPD_PULLDOWN_PIN10	GPIO_PIN_PULLDOWN(20,21)
#define GPIO_PUPD_PULLDOWN_PIN11	GPIO_PIN_PULLDOWN(22,23)
#define GPIO_PUPD_PULLDOWN_PIN12	GPIO_PIN_PULLDOWN(24,25)
#define GPIO_PUPD_PULLDOWN_PIN13	GPIO_PIN_PULLDOWN(26,27)
#define GPIO_PUPD_PULLDOWN_PIN14	GPIO_PIN_PULLDOWN(28,29)
#define GPIO_PUPD_PULLDOWN_PIN15	GPIO_PIN_PULLDOWN(30,31)

#define GPIO_OUTPUT		(BITS(0,1) & ((uint32_t)(1) << 0))
#define GPIO_OUTPUT_PIN0	(GPIO_OUTPUT << 0)
#define GPIO_OUTPUT_PIN1	(GPIO_OUTPUT << 2)
#define GPIO_OUTPUT_PIN2	(GPIO_OUTPUT << 4)
#define GPIO_OUTPUT_PIN3	(GPIO_OUTPUT << 6)
#define GPIO_OUTPUT_PIN4	(GPIO_OUTPUT << 8)
#define GPIO_OUTPUT_PIN5	(GPIO_OUTPUT << 10)
#define GPIO_OUTPUT_PIN6	(GPIO_OUTPUT << 12)
#define GPIO_OUTPUT_PIN7	(GPIO_OUTPUT << 14)
#define GPIO_OUTPUT_PIN8	(GPIO_OUTPUT << 16)
#define GPIO_OUTPUT_PIN9	(GPIO_OUTPUT << 18)
#define GPIO_OUTPUT_PIN10	(GPIO_OUTPUT << 20)
#define GPIO_OUTPUT_PIN11	(GPIO_OUTPUT << 22)
#define GPIO_OUTPUT_PIN12	(GPIO_OUTPUT << 24)
#define GPIO_OUTPUT_PIN13	(GPIO_OUTPUT << 26)
#define GPIO_OUTPUT_PIN14	(GPIO_OUTPUT << 28)
#define GPIO_OUTPUT_PIN15	(GPIO_OUTPUT << 30)
