/* THIS IS AUTO GENERATED CODE */

#ifndef __PIN_H__
#define __PIN_H__

#include <gd32e50x_gpio.h>

/* port A definition */
#define PCB_VER0_PORT		GPIOA
#define PCB_VER0_PIN		GPIO_PIN_0
#define PCB_VER0_EXTI		EXTI_0
#define BOM_VER0_PORT		GPIOA
#define BOM_VER0_PIN		GPIO_PIN_1
#define BOM_VER0_EXTI		EXTI_1
#define MCU_UART1_TX_PORT		GPIOA
#define MCU_UART1_TX_PIN		GPIO_PIN_2
#define MCU_UART1_TX_EXTI		EXTI_2
#define MCU_UART1_RX_PORT		GPIOA
#define MCU_UART1_RX_PIN		GPIO_PIN_3
#define MCU_UART1_RX_EXTI		EXTI_3
#define I_12V_SYS_PORT		GPIOA
#define I_12V_SYS_PIN		GPIO_PIN_4
#define I_12V_SYS_EXTI		EXTI_4
#define PG_VDD_TPU_PORT		GPIOA
#define PG_VDD_TPU_PIN		GPIO_PIN_5
#define PG_VDD_TPU_EXTI		EXTI_5
#define PCIEE_RST_X_MCU_PORT		GPIOA
#define PCIEE_RST_X_MCU_PIN		GPIO_PIN_6
#define PCIEE_RST_X_MCU_EXTI		EXTI_6
#define STATUS_LED0_PORT		GPIOA
#define STATUS_LED0_PIN		GPIO_PIN_7
#define STATUS_LED0_EXTI		EXTI_7
#define I2C1_SCL_PORT		GPIOA
#define I2C1_SCL_PIN		GPIO_PIN_8
#define I2C1_SCL_EXTI		EXTI_8
#define EN_VQPS18_PORT		GPIOA
#define EN_VQPS18_PIN		GPIO_PIN_9
#define EN_VQPS18_EXTI		EXTI_9
#define EN_VDDC_PORT		GPIOA
#define EN_VDDC_PIN		GPIO_PIN_10
#define EN_VDDC_EXTI		EXTI_10
#define EN_VDD_TPU_PORT		GPIOA
#define EN_VDD_TPU_PIN		GPIO_PIN_11
#define EN_VDD_TPU_EXTI		EXTI_11
#define PG_VDDC_PORT		GPIOA
#define PG_VDDC_PIN		GPIO_PIN_12
#define PG_VDDC_EXTI		EXTI_12
#define __PORT		GPIOA
#define __PIN		GPIO_PIN_15
#define __EXTI		EXTI_15

/* port B definition */
#define GPIO1_PORT		GPIOB
#define GPIO1_PIN		GPIO_PIN_0
#define GPIO1_EXTI		EXTI_0
#define GPIO2_PORT		GPIOB
#define GPIO2_PIN		GPIO_PIN_1
#define GPIO2_EXTI		EXTI_1
#define GPIO3_PORT		GPIOB
#define GPIO3_PIN		GPIO_PIN_2
#define GPIO3_EXTI		EXTI_2
#define P08_PWR_GOOD_PORT		GPIOB
#define P08_PWR_GOOD_PIN		GPIO_PIN_3
#define P08_PWR_GOOD_EXTI		EXTI_3
#define I2C1_SDA_PORT		GPIOB
#define I2C1_SDA_PIN		GPIO_PIN_4
#define I2C1_SDA_EXTI		EXTI_4
#define DDR_PWR_GOOD_PORT		GPIOB
#define DDR_PWR_GOOD_PIN		GPIO_PIN_5
#define DDR_PWR_GOOD_EXTI		EXTI_5
#define MCU_INT_PORT		GPIOB
#define MCU_INT_PIN		GPIO_PIN_6
#define MCU_INT_EXTI		EXTI_6
#define PG_VDDIO5_PORT		GPIOB
#define PG_VDDIO5_PIN		GPIO_PIN_7
#define PG_VDDIO5_EXTI		EXTI_7
#define EN_VDDIO5_PORT		GPIOB
#define EN_VDDIO5_PIN		GPIO_PIN_8
#define EN_VDDIO5_EXTI		EXTI_8
#define PG_VDD3V3_PORT		GPIOB
#define PG_VDD3V3_PIN		GPIO_PIN_9
#define PG_VDD3V3_EXTI		EXTI_9
#define MCU_I2C2_SCL_PORT		GPIOB
#define MCU_I2C2_SCL_PIN		GPIO_PIN_10
#define MCU_I2C2_SCL_EXTI		EXTI_10
#define MCU_I2C2_SDA_PORT		GPIOB
#define MCU_I2C2_SDA_PIN		GPIO_PIN_11
#define MCU_I2C2_SDA_EXTI		EXTI_11
#define EN_VDD3V3_PORT		GPIOB
#define EN_VDD3V3_PIN		GPIO_PIN_12
#define EN_VDD3V3_EXTI		EXTI_12
#define AXP_IRQ_PORT		GPIOB
#define AXP_IRQ_PIN		GPIO_PIN_13
#define AXP_IRQ_EXTI		EXTI_13
#define AXP_PWROK_PORT		GPIOB
#define AXP_PWROK_PIN		GPIO_PIN_14
#define AXP_PWROK_EXTI		EXTI_14
#define AXP_PWRON_PORT		GPIOB
#define AXP_PWRON_PIN		GPIO_PIN_15
#define AXP_PWRON_EXTI		EXTI_15

/* port C definition */
#define SYS_RST_X_PORT		GPIOC
#define SYS_RST_X_PIN		GPIO_PIN_13
#define SYS_RST_X_EXTI		EXTI_13
#define EN_VDDIO33_PORT		GPIOC
#define EN_VDDIO33_PIN		GPIO_PIN_14
#define EN_VDDIO33_EXTI		EXTI_14
#define EN_VDDIO18_PORT		GPIOC
#define EN_VDDIO18_PIN		GPIO_PIN_15
#define EN_VDDIO18_EXTI		EXTI_15

#endif
/* AUTO GENERATED CODE END */
