/* THIS IS AUTO GENERATED CODE */

#ifndef __PIN_H__
#define __PIN_H__

#include <gd32e50x_gpio.h>

/* port A definition */
#define PCB_VRE0_PORT		GPIOA
#define PCB_VRE0_PIN		GPIO_PIN_3
#define PCB_VRE0_EXTI		EXTI_3
#define EN_VDD_1V5_PORT		GPIOA
#define EN_VDD_1V5_PIN		GPIO_PIN_4
#define EN_VDD_1V5_EXTI		EXTI_4
#define EN_VDD_1V2_PORT		GPIOA
#define EN_VDD_1V2_PIN		GPIO_PIN_5
#define EN_VDD_1V2_EXTI		EXTI_5
#define EN_VDD_2V5_PORT		GPIOA
#define EN_VDD_2V5_PIN		GPIO_PIN_6
#define EN_VDD_2V5_EXTI		EXTI_6
#define EN_DDR01_VPP_2V5_PORT		GPIOA
#define EN_DDR01_VPP_2V5_PIN		GPIO_PIN_9
#define EN_DDR01_VPP_2V5_EXTI		EXTI_9
#define EN_VDDIO33_PORT		GPIOA
#define EN_VDDIO33_PIN		GPIO_PIN_10
#define EN_VDDIO33_EXTI		EXTI_10
#define EN_DDR_VDD_0V8_PORT		GPIOA
#define EN_DDR_VDD_0V8_PIN		GPIO_PIN_11
#define EN_DDR_VDD_0V8_EXTI		EXTI_11
#define EN_VDDC_PORT		GPIOA
#define EN_VDDC_PIN		GPIO_PIN_12
#define EN_VDDC_EXTI		EXTI_12
#define STATUS_LED0_PORT		GPIOA
#define STATUS_LED0_PIN		GPIO_PIN_15
#define STATUS_LED0_EXTI		EXTI_15

/* port B definition */
#define I_5V_PORT		GPIOB
#define I_5V_PIN		GPIO_PIN_0
#define I_5V_EXTI		EXTI_0
#define I_VDD_12V_PORT		GPIOB
#define I_VDD_12V_PIN		GPIO_PIN_1
#define I_VDD_12V_EXTI		EXTI_1
#define MCU_BOOT1_PORT		GPIOB
#define MCU_BOOT1_PIN		GPIO_PIN_2
#define MCU_BOOT1_EXTI		EXTI_2
#define MCU_I2C2_SCL_PORT		GPIOB
#define MCU_I2C2_SCL_PIN		GPIO_PIN_4
#define MCU_I2C2_SCL_EXTI		EXTI_4
#define MCU_I2C2_SDA_PORT		GPIOB
#define MCU_I2C2_SDA_PIN		GPIO_PIN_5
#define MCU_I2C2_SDA_EXTI		EXTI_5
#define MCU_I2C1_SCL_PORT		GPIOB
#define MCU_I2C1_SCL_PIN		GPIO_PIN_10
#define MCU_I2C1_SCL_EXTI		EXTI_10
#define MCU_I2C1_SDA_PORT		GPIOB
#define MCU_I2C1_SDA_PIN		GPIO_PIN_11
#define MCU_I2C1_SDA_EXTI		EXTI_11
#define PG_DDR_VDD_0V8_PORT		GPIOB
#define PG_DDR_VDD_0V8_PIN		GPIO_PIN_12
#define PG_DDR_VDD_0V8_EXTI		EXTI_12
#define PG_VDDC_PORT		GPIOB
#define PG_VDDC_PIN		GPIO_PIN_13
#define PG_VDDC_EXTI		EXTI_13
#define EN_VDD_1V05_PORT		GPIOB
#define EN_VDD_1V05_PIN		GPIO_PIN_15
#define EN_VDD_1V05_EXTI		EXTI_15

/* port C definition */
#define EN_VDD_1V25_PORT		GPIOC
#define EN_VDD_1V25_PIN		GPIO_PIN_0
#define EN_VDD_1V25_EXTI		EXTI_0
#define EN_3V3_AUX_PCIE_PORT		GPIOC
#define EN_3V3_AUX_PCIE_PIN		GPIO_PIN_1
#define EN_3V3_AUX_PCIE_EXTI		EXTI_1
#define EN_VDD_3V3_PORT		GPIOC
#define EN_VDD_3V3_PIN		GPIO_PIN_2
#define EN_VDD_3V3_EXTI		EXTI_2
#define PG_DDR01_VDDQ_1V2_PORT		GPIOC
#define PG_DDR01_VDDQ_1V2_PIN		GPIO_PIN_6
#define PG_DDR01_VDDQ_1V2_EXTI		EXTI_6
#define EN_DDR23_VDDQ_1V2_PORT		GPIOC
#define EN_DDR23_VDDQ_1V2_PIN		GPIO_PIN_7
#define EN_DDR23_VDDQ_1V2_EXTI		EXTI_7
#define EN_DDR01_VDDQ_1V2_PORT		GPIOC
#define EN_DDR01_VDDQ_1V2_PIN		GPIO_PIN_8
#define EN_DDR01_VDDQ_1V2_EXTI		EXTI_8
#define RGMII_IRQ_H_PORT		GPIOC
#define RGMII_IRQ_H_PIN		GPIO_PIN_9
#define RGMII_IRQ_H_EXTI		EXTI_9
#define MCU_ATX_ON_PORT		GPIOC
#define MCU_ATX_ON_PIN		GPIO_PIN_12
#define MCU_ATX_ON_EXTI		EXTI_12
#define MCU_PS_ON_PORT		GPIOC
#define MCU_PS_ON_PIN		GPIO_PIN_13
#define MCU_PS_ON_EXTI		EXTI_13

/* port D definition */
#define MCU_USART1_TX_PORT		GPIOD
#define MCU_USART1_TX_PIN		GPIO_PIN_5
#define MCU_USART1_TX_EXTI		EXTI_5
#define MCU_USART1_RX_PORT		GPIOD
#define MCU_USART1_RX_PIN		GPIO_PIN_6
#define MCU_USART1_RX_EXTI		EXTI_6
#define MCU_PWER_OK_C_PORT		GPIOD
#define MCU_PWER_OK_C_PIN		GPIO_PIN_8
#define MCU_PWER_OK_C_EXTI		EXTI_8
#define TEST_MOD_PORT		GPIOD
#define TEST_MOD_PIN		GPIO_PIN_9
#define TEST_MOD_EXTI		EXTI_9
#define EN_VQPS18_PORT		GPIOD
#define EN_VQPS18_PIN		GPIO_PIN_11
#define EN_VQPS18_EXTI		EXTI_11
#define CORPOWER_OK_PORT		GPIOD
#define CORPOWER_OK_PIN		GPIO_PIN_12
#define CORPOWER_OK_EXTI		EXTI_12
#define MCU_OK_PORT		GPIOD
#define MCU_OK_PIN		GPIO_PIN_13
#define MCU_OK_EXTI		EXTI_13
#define EN_DDR23_VPP_2V5_PORT		GPIOD
#define EN_DDR23_VPP_2V5_PIN		GPIO_PIN_14
#define EN_DDR23_VPP_2V5_EXTI		EXTI_14
#define PG_DDR23_VDDQ_1V2_PORT		GPIOD
#define PG_DDR23_VDDQ_1V2_PIN		GPIO_PIN_15
#define PG_DDR23_VDDQ_1V2_EXTI		EXTI_15

/* port E definition */
#define EN_VDD_1V05_ASM_PORT		GPIOE
#define EN_VDD_1V05_ASM_PIN		GPIO_PIN_0
#define EN_VDD_1V05_ASM_EXTI		EXTI_0
#define EN_VDD_2V5_ASM_PORT		GPIOE
#define EN_VDD_2V5_ASM_PIN		GPIO_PIN_1
#define EN_VDD_2V5_ASM_EXTI		EXTI_1
#define EN_VDD_PCIE_H_1V8_PORT		GPIOE
#define EN_VDD_PCIE_H_1V8_PIN		GPIO_PIN_2
#define EN_VDD_PCIE_H_1V8_EXTI		EXTI_2
#define EN_VDD_PCIE_D_0V8_PORT		GPIOE
#define EN_VDD_PCIE_D_0V8_PIN		GPIO_PIN_3
#define EN_VDD_PCIE_D_0V8_EXTI		EXTI_3
#define EN_VDD_PLL_0V8_PORT		GPIOE
#define EN_VDD_PLL_0V8_PIN		GPIO_PIN_4
#define EN_VDD_PLL_0V8_EXTI		EXTI_4
#define EN_VDDIO18_PORT		GPIOE
#define EN_VDDIO18_PIN		GPIO_PIN_5
#define EN_VDDIO18_EXTI		EXTI_5
#define SYS_RST_X_H_PORT		GPIOE
#define SYS_RST_X_H_PIN		GPIO_PIN_6
#define SYS_RST_X_H_EXTI		EXTI_6
#define MCU_GPIO1_PORT		GPIOE
#define MCU_GPIO1_PIN		GPIO_PIN_7
#define MCU_GPIO1_EXTI		EXTI_7
#define MCU_GPIO2_PORT		GPIOE
#define MCU_GPIO2_PIN		GPIO_PIN_8
#define MCU_GPIO2_EXTI		EXTI_8
#define MCU_GPIO3_PORT		GPIOE
#define MCU_GPIO3_PIN		GPIO_PIN_9
#define MCU_GPIO3_EXTI		EXTI_9
#define MCU_GPIO4_PORT		GPIOE
#define MCU_GPIO4_PIN		GPIO_PIN_10
#define MCU_GPIO4_EXTI		EXTI_10
#define MCU_GPIO5_PORT		GPIOE
#define MCU_GPIO5_PIN		GPIO_PIN_11
#define MCU_GPIO5_EXTI		EXTI_11
#define MCU_GPIO6_PORT		GPIOE
#define MCU_GPIO6_PIN		GPIO_PIN_12
#define MCU_GPIO6_EXTI		EXTI_12
#define MCU_GPIO7_PORT		GPIOE
#define MCU_GPIO7_PIN		GPIO_PIN_13
#define MCU_GPIO7_EXTI		EXTI_13
#define MCU_GPIO8_PORT		GPIOE
#define MCU_GPIO8_PIN		GPIO_PIN_14
#define MCU_GPIO8_EXTI		EXTI_14

#endif
/* AUTO GENERATED CODE END */
