/* THIS IS AUTO GENERATED CODE */

#ifndef __PIN_H__
#define __PIN_H__

#include <gd32e50x_gpio.h>

/* port A definition */
#define CURRENT_SYS_12V_PORT		GPIOA
#define CURRENT_SYS_12V_PIN		GPIO_PIN_0
#define CURRENT_SYS_12V_EXTI		EXTI_0
#define CURRENT_PCIE_12V_PORT		GPIOA
#define CURRENT_PCIE_12V_PIN		GPIO_PIN_1
#define CURRENT_PCIE_12V_EXTI		EXTI_1
#define CURRENT_PCIE_3V3_PORT		GPIOA
#define CURRENT_PCIE_3V3_PIN		GPIO_PIN_2
#define CURRENT_PCIE_3V3_EXTI		EXTI_2
#define MCU_I2C3_SCL_PORT		GPIOA
#define MCU_I2C3_SCL_PIN		GPIO_PIN_8
#define MCU_I2C3_SCL_EXTI		EXTI_8
#define EN_VP_C2C_PORT		GPIOA
#define EN_VP_C2C_PIN		GPIO_PIN_9
#define EN_VP_C2C_EXTI		EXTI_9
#define EN_DDR_VDD_PORT		GPIOA
#define EN_DDR_VDD_PIN		GPIO_PIN_10
#define EN_DDR_VDD_EXTI		EXTI_10
#define EN_VDDR_PORT		GPIOA
#define EN_VDDR_PIN		GPIO_PIN_11
#define EN_VDDR_EXTI		EXTI_11
#define EN_VDDC_PORT		GPIOA
#define EN_VDDC_PIN		GPIO_PIN_12
#define EN_VDDC_EXTI		EXTI_12
#define STATUS_LED0_PORT		GPIOA
#define STATUS_LED0_PIN		GPIO_PIN_15
#define STATUS_LED0_EXTI		EXTI_15

/* port B definition */
#define MCU_BOOT1_PORT		GPIOB
#define MCU_BOOT1_PIN		GPIO_PIN_2
#define MCU_BOOT1_EXTI		EXTI_2
#define MCU_I2C1_SCL_PORT		GPIOB
#define MCU_I2C1_SCL_PIN		GPIO_PIN_6
#define MCU_I2C1_SCL_EXTI		EXTI_6
#define MCU_I2C1_SDA_PORT		GPIOB
#define MCU_I2C1_SDA_PIN		GPIO_PIN_7
#define MCU_I2C1_SDA_EXTI		EXTI_7
#define CARD_PWR_PRES_PORT		GPIOB
#define CARD_PWR_PRES_PIN		GPIO_PIN_8
#define CARD_PWR_PRES_EXTI		EXTI_8
#define CARD_PWR_STA_PORT		GPIOB
#define CARD_PWR_STA_PIN		GPIO_PIN_9
#define CARD_PWR_STA_EXTI		EXTI_9
#define MCU_I2C2_SCL_PORT		GPIOB
#define MCU_I2C2_SCL_PIN		GPIO_PIN_10
#define MCU_I2C2_SCL_EXTI		EXTI_10
#define MCU_I2C2_SDA_PORT		GPIOB
#define MCU_I2C2_SDA_PIN		GPIO_PIN_11
#define MCU_I2C2_SDA_EXTI		EXTI_11
#define EN_VDD_1V2_PORT		GPIOB
#define EN_VDD_1V2_PIN		GPIO_PIN_12
#define EN_VDD_1V2_EXTI		EXTI_12
#define EN_DDR_VAA_PORT		GPIOB
#define EN_DDR_VAA_PIN		GPIO_PIN_13
#define EN_DDR_VAA_EXTI		EXTI_13
#define ATX_CTRL_PORT		GPIOB
#define ATX_CTRL_PIN		GPIO_PIN_14
#define ATX_CTRL_EXTI		EXTI_14
#define CLK_LOSb_PORT		GPIOB
#define CLK_LOSb_PIN		GPIO_PIN_15
#define CLK_LOSb_EXTI		EXTI_15

/* port C definition */
#define PCB_VER_PORT		GPIOC
#define PCB_VER_PIN		GPIO_PIN_0
#define PCB_VER_EXTI		EXTI_0
#define BOM_VER_PORT		GPIOC
#define BOM_VER_PIN		GPIO_PIN_1
#define BOM_VER_EXTI		EXTI_1
#define EN_VPH_C2C_PORT		GPIOC
#define EN_VPH_C2C_PIN		GPIO_PIN_6
#define EN_VPH_C2C_EXTI		EXTI_6
#define MCU_I2C3_SDA_PORT		GPIOC
#define MCU_I2C3_SDA_PIN		GPIO_PIN_9
#define MCU_I2C3_SDA_EXTI		EXTI_9
#define EN_DDR_VDD1_PORT		GPIOC
#define EN_DDR_VDD1_PIN		GPIO_PIN_10
#define EN_DDR_VDD1_EXTI		EXTI_10
#define VDDR_WAKE_PORT		GPIOC
#define VDDR_WAKE_PIN		GPIO_PIN_12
#define VDDR_WAKE_EXTI		EXTI_12
#define PCIE4_L0_RESET_X_H_PORT		GPIOC
#define PCIE4_L0_RESET_X_H_PIN		GPIO_PIN_13
#define PCIE4_L0_RESET_X_H_EXTI		EXTI_13

/* port D definition */
#define PG_DDR_VDDQ_R_PORT		GPIOD
#define PG_DDR_VDDQ_R_PIN		GPIO_PIN_0
#define PG_DDR_VDDQ_R_EXTI		EXTI_0
#define PG_DDR_VDD2H_R_PORT		GPIOD
#define PG_DDR_VDD2H_R_PIN		GPIO_PIN_1
#define PG_DDR_VDD2H_R_EXTI		EXTI_1
#define PCIE_RST_X_PORT		GPIOD
#define PCIE_RST_X_PIN		GPIO_PIN_2
#define PCIE_RST_X_EXTI		EXTI_2
#define MCU_USART1_TX_PORT		GPIOD
#define MCU_USART1_TX_PIN		GPIO_PIN_5
#define MCU_USART1_TX_EXTI		EXTI_5
#define MCU_USART1_RX_PORT		GPIOD
#define MCU_USART1_RX_PIN		GPIO_PIN_6
#define MCU_USART1_RX_EXTI		EXTI_6
#define EN_VDD_3V3_PORT		GPIOD
#define EN_VDD_3V3_PIN		GPIO_PIN_8
#define EN_VDD_3V3_EXTI		EXTI_8
#define EN_VDD_PLL_PORT		GPIOD
#define EN_VDD_PLL_PIN		GPIO_PIN_10
#define EN_VDD_PLL_EXTI		EXTI_10
#define MCU_OK_PORT		GPIOD
#define MCU_OK_PIN		GPIO_PIN_13
#define MCU_OK_EXTI		EXTI_13

/* port E definition */
#define PWR_SENSE1_PORT		GPIOE
#define PWR_SENSE1_PIN		GPIO_PIN_0
#define PWR_SENSE1_EXTI		EXTI_0
#define PWR_SENSE0_PORT		GPIOE
#define PWR_SENSE0_PIN		GPIO_PIN_1
#define PWR_SENSE0_EXTI		EXTI_1
#define PG_VDDR_PORT		GPIOE
#define PG_VDDR_PIN		GPIO_PIN_2
#define PG_VDDR_EXTI		EXTI_2
#define SYS_RST_X_H_PORT		GPIOE
#define SYS_RST_X_H_PIN		GPIO_PIN_6
#define SYS_RST_X_H_EXTI		EXTI_6
#define PG_DDR_VDD_PORT		GPIOE
#define PG_DDR_VDD_PIN		GPIO_PIN_7
#define PG_DDR_VDD_EXTI		EXTI_7
#define PG_VDDC_PORT		GPIOE
#define PG_VDDC_PIN		GPIO_PIN_8
#define PG_VDDC_EXTI		EXTI_8
#define PG_VP_C2C_PORT		GPIOE
#define PG_VP_C2C_PIN		GPIO_PIN_9
#define PG_VP_C2C_EXTI		EXTI_9
#define PG_DDR_VDDQ_L_PORT		GPIOE
#define PG_DDR_VDDQ_L_PIN		GPIO_PIN_10
#define PG_DDR_VDDQ_L_EXTI		EXTI_10
#define PG_DDR_VDD2H_L_PORT		GPIOE
#define PG_DDR_VDD2H_L_PIN		GPIO_PIN_11
#define PG_DDR_VDD2H_L_EXTI		EXTI_11
#define EN_DDR_VDD2H_PORT		GPIOE
#define EN_DDR_VDD2H_PIN		GPIO_PIN_12
#define EN_DDR_VDD2H_EXTI		EXTI_12
#define EN_VDD_5V_PORT		GPIOE
#define EN_VDD_5V_PIN		GPIO_PIN_13
#define EN_VDD_5V_EXTI		EXTI_13
#define EN_DDR_VDDQ_PORT		GPIOE
#define EN_DDR_VDDQ_PIN		GPIO_PIN_14
#define EN_DDR_VDDQ_EXTI		EXTI_14
#define EN_VDD_1V8_PORT		GPIOE
#define EN_VDD_1V8_PIN		GPIO_PIN_15
#define EN_VDD_1V8_EXTI		EXTI_15

#endif
/* AUTO GENERATED CODE END */
